"use client";

import Head from "next/head";
import Image from "next/legacy/image";
import { useState, useEffect } from "react";

export default function Home() {
  const [questionText, setQuestionText] = useState("");
  const [surveyId, setSurveyId] = useState("");
  const [showThankYouModal, setShowThankYouModal] = useState(false);

  useEffect(() => {
    // Replace 'http://your-nestjs-api.com/questions/current' with your actual NestJS endpoint
    fetch("http://localhost:3000/survey/user/1")
      .then((response) => response.json())
      .then((data) => {
        setQuestionText(data.content);
        setSurveyId(data.id);
      })
      .catch((error) => console.error("Error fetching question:", error));
  }, []);

  const postReview = async (reviewType: string) => {
    const reviewData = {
      surveyId: surveyId, // Assuming you have the survey ID
      answer: reviewType,
      // Add other necessary data, like user ID, if applicable
    };

    try {
      await fetch("http://localhost:3000/review/makeReview", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(reviewData),
      });
    } catch (error) {
      console.error("Error posting review:", error);
    }

    setShowThankYouModal(true); // Show thank you modal after posting review
  };

  const handleHappyClick = () => {
    postReview("Happy");
    // Additional actions
  };

  const handleNeutralClick = () => {
    postReview("Neutral");
    // Additional actions
  };

  const handleSadClick = () => {
    postReview("Sad");
    // Additional actions
  };

  return (
    <>
      <Head>
        <title>Custom Page with Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Full screen background image with logo centered at the top */}
      <div className="relative w-full min-h-screen bg-cover bg-no-repeat">
        {/* Background Image */}
        <Image
          src="/background.jpg"
          alt="Background"
          layout="fill"
          objectFit="cover"
          className="z-0"
        />

        {/* Logo at the top center of the page */}
        <div className="absolute top-10 left-1/2 transform -translate-x-1/2 z-10">
          <Image src="/poster-logo.png" alt="Logo" width={100} height={100} />
        </div>

        {/* Enlarged white area at the bottom of the viewport with a question and emoticon icons */}
        {/* Increasing the padding and adjusting the top padding to make the white area larger */}
        <div className="fixed inset-x-0 bottom-0 p-8 bg-white z-20 pb-32 pt-12 rounded-3xl">
          {/* Mascot at the top right of the white area, size increased */}
          <div className="absolute top-0 left-1/4 transform translate-y-[-100%] mr-4">
            <Image
              src="/opedo.png"
              alt="Mascot"
              width={200} /* Size increased */
              height={200} /* Size increased */
            />
          </div>

          {/* Question text, size increased */}
          <p className="text-center text-xl mb-8 text-black">{questionText}</p>

          {/* Emoticons, size increased */}
          <div className="flex justify-center space-x-20">
            <div onClick={handleHappyClick}>
              <Image src="/happy.png" alt="Happy" width={70} height={70} />
            </div>
            <div onClick={handleNeutralClick}>
              <Image src="/neutral.png" alt="Neutral" width={70} height={70} />
            </div>
            <div onClick={handleSadClick}>
              <Image src="/sad.png" alt="Sad" width={70} height={70} />
            </div>
          </div>
          {showThankYouModal && (
            <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
              <div className="bg-white p-6 rounded-lg shadow-lg text-center">
                <h2 className="text-2xl font-bold mb-4">Thank You!</h2>
                <p>Your feedback is appreciated.</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
