'use client'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {

  // Functions to handle click events for each icon
  const handleHappyClick = () => {
    console.log('Happy clicked');
    // You can add more actions here
  }

  const handleNeutralClick = () => {
    console.log('Neutral clicked');
    // You can add more actions here
  }

  const handleSadClick = () => {
    console.log('Sad clicked');
    // You can add more actions here
  }
  return (
    <>
      <Head>
        <title>Custom Page with Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Full screen background image with logo centered at the top */}
      <div className="relative w-full min-h-screen bg-cover bg-no-repeat">
        {/* Background Image */}
        <Image
          src="/background.jpg"
          alt="Background"
          layout="fill"
          objectFit="cover"
          className="z-0"
        />

        {/* Logo at the top center of the page */}
        <div className="absolute top-10 left-1/2 transform -translate-x-1/2 z-10">
          <Image
            src="/poster-logo.png"
            alt="Logo"
            width={100}
            height={100}
          />
        </div>

        {/* Enlarged white area at the bottom of the viewport with a question and emoticon icons */}
        {/* Increasing the padding and adjusting the top padding to make the white area larger */}
        <div className="fixed inset-x-0 bottom-0 p-8 bg-white z-20 pb-32 pt-12 rounded-3xl">
          {/* Mascot at the top right of the white area, size increased */}
          <div className="absolute top-0 left-1/4 transform translate-y-[-100%] mr-4">
            <Image
              src="/opedo.png"
              alt="Mascot"
              width={200} /* Size increased */
              height={200} /* Size increased */
            />
          </div>

          {/* Question text, size increased */}
          <p className="text-center text-xl mb-8 text-black">Hizmetimizden memnun kaldınız mı?</p>

          {/* Emoticons, size increased */}
          <div className="flex justify-center space-x-20">
          <div onClick={handleHappyClick}>
              <Image src="/happy.png" alt="Happy" width={70} height={70} />
            </div>
            <div onClick={handleNeutralClick}>
              <Image src="/neutral.png" alt="Neutral" width={70} height={70} />
            </div>
            <div onClick={handleSadClick}>
              <Image src="/sad.png" alt="Sad" width={70} height={70} />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
